[assembly: System.Reflection.AssemblyCopyright("Copyright © 2025 HardCodeDev")]
[assembly: System.Reflection.AssemblyCompany("HardCodeDev")]
[assembly: System.Reflection.AssemblyFileVersion("1.0.0")]
[assembly: System.Reflection.AssemblyInformationalVersion("1.0.0")]
[assembly: System.Reflection.AssemblyProduct("BatchLama")]
[assembly: System.Reflection.AssemblyTitle("BatchLama")]
[assembly: System.Reflection.AssemblyVersion("1.0.0")]